### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by Ernane85** [open-pulse/OpenPulse#120]
Hello guys! I got the following error running pulse.py:

Traceback (most recent call last):
  File "C:\Users\Ernane\Downloads\OpenPulse-master\pulse.py", line 4, in <module>
    import vtk
  File "C:\Users\Ernane\AppData\Local\Programs\Python\Python37\lib\site-packages\vtk.py", line 31, in <module>
    all_m = importlib.import_module('vtkmodules.all')
  File "C:\Users\Ernane\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Ernane\AppData\Local\Programs\Python\Python37\lib\site-packages\vtkmodules\all.py", line 7, in <module>
    from .vtkCommonCore import *
ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.

I would appreciate any clue on this issue.
Best regards,
Ernane Silva

**Comment by olavosilva** [comment]
Hi, Ernane!

Have you installed the requirements? pip install -r requirements.txt
Or, could you try to reinstall vtk? pip install vtk --user

Thank you for helping us improve the software!

**Comment by Ernane85** [comment]
Hi, Olavo!

I had already installed all the requirements following the first instruction you provided and it did not work. Then, I tried to uninstall everything and reinstalling it, but nothing changed. I also tried to reinstall vtk, as you sugggested. No success. The same message from my last post occurs.

**Comment by olavosilva** [comment]
Hi, Ernane!

Could you, please, try to change from powershell to command prompt (as in the figure below)?

![image](https://user-images.githubusercontent.com/47498314/147232079-ff71166a-1d33-4093-902a-fc84255e48f0.png)

**Comment by olavosilva** [comment]
No error was observed in new versions.
