### ISSUE TITLE
Potential bug with acoustic analysis

### ISSUE THREAD

**Issue by HenryC15** [open-pulse/OpenPulse#39]
**Operating system:**
Windows 10 pro 2019
(64 bit)

**Versions:**
Python 3.7.7
Openpulse download 27-11-2020

**Details of issue**
I can successfully run structural analyses, but acoustic (or acoustic modal) analyses return the following error (openpulse then terminates):

```
Traceback (most recent call last):
  File "C:\Users\Henry\OpenPulse-master\OpenPulse-master\pulse\uix\treeUi.py", line 353, in on_click_item
    self.mainWindow.getInputWidget().runAnalysis()
  File "C:\Users\Henry\OpenPulse-master\OpenPulse-master\pulse\uix\inputUi.py", line 429, in runAnalysis
    solve = self.project.get_acoustic_solve()
  File "C:\Users\Henry\OpenPulse-master\OpenPulse-master\pulse\project.py", line 883, in get_acoustic_solve
    return SolutionAcoustic(self.mesh, self.frequencies)
  File "C:\Users\Henry\OpenPulse-master\OpenPulse-master\pulse\processing\solution_acoustic.py", line 16, in __init__
    self.assembly = AssemblyAcoustic(mesh, frequencies)
  File "C:\Users\Henry\OpenPulse-master\OpenPulse-master\pulse\processing\assembly_acoustic.py", line 34, in __init__
    self.pipe_gdofs = mesh.get_pipe_elements_global_dofs()
  File "C:\Users\Henry\OpenPulse-master\OpenPulse-master\pulse\preprocessing\mesh.py", line 938, in get_pipe_elements_global_dofs
    pipe_gdofs = np.delete(all_indexes, self.beam_gdofs)
  File "<__array_function__ internals>", line 6, in delete
  File "C:\Users\Henry\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: arrays used as indices must be of integer (or boolean) type
```
I have also tried using in a conda environment, using Python 3.8, and on alternative machines, always with the same error returned.

**Comment by olavosilva** [comment]
Hi HenryC15. Our team fixed this bug. Could you test again?
Thank you very much!
