### ISSUE TITLE
Error when 'Set Cross Section' is selected

### ISSUE THREAD

**Issue by raphaeltimbo** [open-pulse/OpenPulse#62]
If 'Set Cross Section' is selected with no lines in selection I get the following error:

```
(openpulse) C:\Users\up49\OpenPulse>python pulse.py
Total number of loaded entities 49.
Traceback (most recent call last):
  File "C:\Users\up49\OpenPulse\pulse\uix\menu\MenuItems.py", line 302, in on_click_item
    if self.mainWindow.getInputWidget().set_cross_section():
  File "C:\Users\up49\OpenPulse\pulse\uix\inputUi.py", line 138, in set_cross_section
    read = CrossSectionInput(   self.project,
  File "C:\Users\up49\OpenPulse\pulse\uix\user_input\model\setup\structural\crossSectionInput.py", line 173, in __init__
    self.write_ids(self.lines_to_update_cross_section)
  File "C:\Users\up49\OpenPulse\pulse\uix\user_input\model\setup\structural\crossSectionInput.py", line 235, in write_ids
    for _id in list_ids:
TypeError: 'NoneType' object is not iterable
```

I am using:
OS: Windows
Python: 3.8.8
Running the version from commit a118e2938063ad18f0211915fb2d76b381f0f8f8

**Comment by JacsonGilVargas** [comment]
Dear user, this problem has already been solved in the Beta branch. As soon as possible, we will merge the Beta with the Master branch to fix the problem at the Master's version too.

**Comment by olavosilva** [comment]
It's OK.
