### ISSUE TITLE
Error trying to run the package on linux

### ISSUE THREAD

**Issue by raphaeltimbo** [open-pulse/OpenPulse#8]
When I try to run the package on linux I get the following error:

```
(openpulse)  raphael@raphael-G750JH  ~/OpenPulse   master  python pulse.py             Traceback (most recent call last):
  File "pulse.py", line 4, in <module>
    from pulse.uix.mainWindow import MainWindow
  File "/home/raphael/OpenPulse/pulse/uix/mainWindow.py", line 14, in <module>
    from pulse.project import Project
  File "/home/raphael/OpenPulse/pulse/project.py", line 1, in <module>
    from pulse.preprocessing.mesh import Mesh
  File "/home/raphael/OpenPulse/pulse/preprocessing/mesh.py", line 4, in <module>
    import gmsh
  File "/home/raphael/anaconda3/lib/python3.7/site-packages/gmsh-4.5.6-Linux64-sdk/lib/gmsh.py", line 39, in <module>
    lib = CDLL(libpath)
  File "/home/raphael/anaconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/raphael/anaconda3/bin/../lib/./libpng16.so.16)

```

**Comment by raphaeltimbo** [comment]
Solved this using: https://stackoverflow.com/a/48579743/5726899
Maybe this could be added to the package setup.

**Comment by raphaeltimbo** [comment]
I have edited the comment to state that the proposed solution can cause problem to the user system. Since the software is being developed for Windows I will close this issue.
